@extends('layouts.fleetman')

@section('title', 'Drivers | FleetMan')
@section('mobile-title', 'Drivers')

@section('content')
<div class="page-section">
    <div id="driverAddPage">
        <x-fleetman.topbar :items="[['label' => 'Add Driver']]">
            <x-slot:actions><button type="button" class="btn light" data-page-target="driverListPage">← Driver List</button></x-slot:actions>
        </x-fleetman.topbar>

        <x-fleetman.title-card title="Add New Driver" subtitle="A clean, step-by-step form for office staff. Keep the must-have fields first. Put extra information later.">
            <x-slot:action><button type="button" class="btn secondary" id="loadDriverSampleBtn">Use sample data</button></x-slot:action>
        </x-fleetman.title-card>

        <div class="layout">
            <div>
                <x-fleetman.section-card title="1. Basic Driver Information" description="Use simple names and mobile number. Driver ID is generated by the system.">
                    <div class="grid4">
                        <x-fleetman.input id="driverId" label="Driver ID" required readonly />
                        <x-fleetman.input id="driverFullName" label="Full Name" required placeholder="Example: Md. Karim Hossain" />
                        <x-fleetman.input id="driverFatherName" label="Father's Name" required placeholder="Example: Md. Abdul Mannan" />
                        <x-fleetman.input id="driverMotherName" label="Mother's Name" required placeholder="Example: Mst. Amena Begum" />
                        <x-fleetman.input id="driverWhatsapp" label="WhatsApp Number" placeholder="Example: 01712000000" />
                        <x-fleetman.input id="driverEmail" label="Email" type="email" placeholder="Example: driver@email.com" />
                        <x-fleetman.input id="driverDob" label="Date of Birth" type="date" />
                        <x-fleetman.input id="driverAge" label="Age" type="number" placeholder="Auto or manual" />
                        <x-fleetman.input id="driverNid" label="NID" required placeholder="Example: 19891234567890123" />
                        <x-fleetman.input id="driverReference" label="Reference" placeholder="Example: Vendor / Staff reference" />
                    </div>
                </x-fleetman.section-card>

                <x-fleetman.section-card title="2. Contact Numbers" description="Add one or more contact numbers. Choose the type for each number. If the contact is a relative, a relationship field will appear.">
                    <div id="driverContacts"></div>
                    <button type="button" class="btn secondary" id="addDriverContactBtn" style="margin-top:10px">＋ Add Contact Number</button>
                </x-fleetman.section-card>

                <x-fleetman.section-card title="3. License & Work Setup" description="Keep license type, validity and payment terms clear. These are needed for assignment and compliance.">
                    <div class="grid3">
                        <x-fleetman.input id="driverLicenseNo" label="Driving License No." required placeholder="Example: DL-DHK-443219" />
                        <x-fleetman.select id="driverLicenseType" label="License Type" required :options="$fleetman['options']['driver_license_types']" placeholder="Select license type" />
                        <x-fleetman.input id="driverLicenseValidity" label="License Validity Date" type="date" required hint="Use exact expiry date instead of typing date ranges." />
                        <x-fleetman.input id="driverSalary" label="Salary" type="number" required placeholder="Example: 25000" />
                        <x-fleetman.select id="driverSalaryTenure" label="Salary Tenure" required :options="$fleetman['options']['driver_salary_tenures']" />
                        <x-fleetman.input id="driverOtRate" label="Overtime Rate" type="number" value="50" />
                        <x-fleetman.input id="driverWorkingHour" label="Regular Working Hour" type="number" value="270" required hint="Monthly target hour. Example: 270." />
                        <x-fleetman.select id="driverVendor" label="Vendor / Contractor" :options="array_merge(['Own Payroll'], $fleetman['options']['vendors'])" placeholder="None" />
                        <x-fleetman.select id="driverStatus" label="Driver Status" :options="$fleetman['options']['driver_statuses']" />
                    </div>
                    <div class="field" style="margin-top:16px">
                        <label>Preferred Duty Type</label>
                        <div class="choice-grid">
                            @foreach($fleetman['options']['driver_duty_types'] as $duty)
                                <label class="choice"><input type="radio" name="driverDuty" value="{{ $duty['value'] }}"><span>{{ $duty['title'] }}</span><small>{{ $duty['description'] }}</small></label>
                            @endforeach
                        </div>
                    </div>
                </x-fleetman.section-card>

                <x-fleetman.section-card title="4. Address & Notes" description="Keep full address so the team can contact the driver when needed.">
                    <div class="grid">
                        <x-fleetman.textarea id="driverPresentAddress" label="Present Address" required placeholder="House, road, area, district" />
                        <x-fleetman.textarea id="driverPermanentAddress" label="Permanent Address" required placeholder="Village/house, post office, thana, district" />
                    </div>
                    <div style="margin-top:16px"><x-fleetman.textarea id="driverAbout" label="About / Remarks" placeholder="Any important note about the driver" /></div>
                </x-fleetman.section-card>

                <x-fleetman.section-card title="5. Photo & Documents" description="Write document names clearly. Upload files and optionally set reminders.">
                    <x-slot:action><button type="button" class="btn secondary" id="addDriverDocumentBtn">+ Add Document</button></x-slot:action>
                    <div class="photo-box" style="margin-bottom:14px"><div class="photo-avatar">🧑‍✈️</div><div class="field" style="flex:1"><label for="driverPhoto">Driver Photo</label><input id="driverPhoto" type="file" accept="image/*"><div class="hint">Allowed: png, jpg, jpeg, webp. Prototype stores file name only.</div></div></div>
                    <div id="driverDocuments"></div>
                </x-fleetman.section-card>
            </div>
            <aside>
                <x-fleetman.side-note title="Suggested redesign decisions"><ul><li>Split the large form into clear sections.</li><li>Replace long confusing fields with dropdowns and radio cards.</li><li>Use exact date for license validity.</li><li>Keep documents flexible with custom names.</li><li>After saving, user goes to Driver List page.</li></ul></x-fleetman.side-note>
                <div class="required-box"><b>Minimum required to save:</b><br>Full name, NID, driving license, license type, license validity, salary, working hour, present and permanent address.</div>
                <x-fleetman.side-note title="Sample documents" style="margin-top:14px"><ul><li>NID scan copy</li><li>Driving license copy</li><li>Police verification</li><li>Medical fitness certificate</li><li>Appointment letter</li><li>Training certificate</li></ul></x-fleetman.side-note>
            </aside>
        </div>
        <div class="save-bar"><button type="button" class="btn light" id="resetDriverBtn">Clear</button><button type="button" class="btn secondary" id="saveDriverDraftBtn">Save as Draft</button><button type="button" class="btn primary" id="saveDriverBtn">Save Driver & Go to List</button></div>
    </div>

    <div id="driverListPage" class="hidden">
        <x-fleetman.topbar :items="[['label' => 'Driver List']]">
            <x-slot:actions><button type="button" class="btn primary" id="newDriverBtn">+ Add Driver</button></x-slot:actions>
        </x-fleetman.topbar>
        <x-fleetman.title-card title="Drivers" subtitle="All saved drivers appear here. Search, filter, view, edit or export."><x-slot:action><button type="button" class="btn secondary" id="exportDriversBtn">Export CSV</button></x-slot:action></x-fleetman.title-card>
        <div class="kpi"><x-fleetman.kpi-card id="driverKpiTotal" label="Total drivers" /><x-fleetman.kpi-card id="driverKpiActive" label="Active" /><x-fleetman.kpi-card id="driverKpiExpired" label="Expired soon" /><x-fleetman.kpi-card id="driverKpiDocs" label="Total documents" /></div>
        <div class="card">
            <div class="filters">
                <input id="driverSearch" placeholder="Search by name, mobile, NID, license">
                <x-fleetman.select id="driverFilterStatus" label="" :options="$fleetman['options']['driver_statuses']" placeholder="All status" />
                <x-fleetman.select id="driverFilterLicense" label="" :options="$fleetman['options']['driver_license_types']" placeholder="All license" />
                <x-fleetman.select id="driverFilterTenure" label="" :options="$fleetman['options']['driver_salary_tenures']" placeholder="All salary type" />
                <button type="button" class="btn light" id="clearDriverFiltersBtn">Clear Filter</button>
            </div>
            <div class="table-wrap driver-table"><table><thead><tr><th>Driver</th><th>Contact</th><th>License</th><th>Validity</th><th>Salary</th><th>Working Hour</th><th>Vendor</th><th>Docs</th><th>Status</th><th>Action</th></tr></thead><tbody id="driverTbody"></tbody></table></div>
        </div>
    </div>
</div>
@endsection
